-- ============================================================================
-- 山商信息通 · AI 校园助手第一阶段
-- 作用：创建私有知识库、匿名额度计数与不含聊天正文的用量日志。
-- 注意：这是增量脚本，不要用它替代或重跑 supabase-schema.sql。
-- ============================================================================

begin;

create table if not exists public.knowledge_documents (
    id uuid primary key default gen_random_uuid(),
    slug text not null unique,
    title text not null,
    category text not null,
    summary text not null default '',
    content text not null,
    source_url text,
    source_type text not null default 'curated'
        check (source_type in ('curated', 'official_notice', 'manual')),
    source_date date,
    verified_at timestamptz,
    status text not null default 'draft'
        check (status in ('draft', 'published', 'archived')),
    checksum text not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists idx_knowledge_documents_status_category
    on public.knowledge_documents (status, category);

create index if not exists idx_knowledge_documents_updated_at
    on public.knowledge_documents (updated_at desc);

create table if not exists public.ai_rate_limits (
    client_hash text not null,
    window_start timestamptz not null,
    request_count integer not null default 0 check (request_count >= 0),
    updated_at timestamptz not null default timezone('utc'::text, now()),
    primary key (client_hash, window_start)
);

create index if not exists idx_ai_rate_limits_updated_at
    on public.ai_rate_limits (updated_at);

create table if not exists public.ai_usage (
    id bigint generated by default as identity primary key,
    client_hash text not null,
    provider text not null,
    model text not null,
    retrieval_count integer not null default 0,
    input_chars integer not null default 0,
    output_chars integer not null default 0,
    latency_ms integer,
    status text not null check (status in ('ok', 'no_match', 'rate_limited', 'error')),
    created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists idx_ai_usage_created_at
    on public.ai_usage (created_at desc);

alter table public.knowledge_documents enable row level security;
alter table public.ai_rate_limits enable row level security;
alter table public.ai_usage enable row level security;

-- AI 数据只能由服务端 Edge Function 或受信任的同步脚本访问。
revoke all on table public.knowledge_documents from public, anon, authenticated;
revoke all on table public.ai_rate_limits from public, anon, authenticated;
revoke all on table public.ai_usage from public, anon, authenticated;
revoke all on sequence public.ai_usage_id_seq from public, anon, authenticated;

grant select, insert, update, delete on table public.knowledge_documents to service_role;
grant select, insert, update, delete on table public.ai_rate_limits to service_role;
grant select, insert on table public.ai_usage to service_role;
grant usage, select on sequence public.ai_usage_id_seq to service_role;

-- 原子消费匿名额度。函数为 SECURITY DEFINER，但只授权 service_role 调用，
-- 且显式清空 search_path，避免通过 exposed public schema 提权。
create or replace function public.consume_ai_quota(
    p_client_hash text,
    p_limit integer default 12,
    p_window_minutes integer default 60
)
returns table (
    allowed boolean,
    remaining integer,
    reset_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_limit integer := greatest(1, least(coalesce(p_limit, 12), 1000));
    v_window_minutes integer := greatest(1, least(coalesce(p_window_minutes, 60), 1440));
    v_window_seconds integer;
    v_window_start timestamptz;
    v_count integer;
begin
    if p_client_hash is null or length(p_client_hash) < 16 then
        raise exception 'invalid client hash';
    end if;

    v_window_seconds := v_window_minutes * 60;
    v_window_start := to_timestamp(
        floor(extract(epoch from timezone('utc'::text, now())) / v_window_seconds)
        * v_window_seconds
    );

    insert into public.ai_rate_limits (client_hash, window_start, request_count, updated_at)
    values (p_client_hash, v_window_start, 1, timezone('utc'::text, now()))
    on conflict (client_hash, window_start)
    do update set
        request_count = public.ai_rate_limits.request_count + 1,
        updated_at = timezone('utc'::text, now())
    returning request_count into v_count;

    return query
    select
        v_count <= v_limit,
        greatest(v_limit - v_count, 0),
        v_window_start + make_interval(mins => v_window_minutes);
end;
$$;

revoke all on function public.consume_ai_quota(text, integer, integer)
    from public, anon, authenticated;
grant execute on function public.consume_ai_quota(text, integer, integer)
    to service_role;

commit;
