-- ============================================================================
-- 山商信息通 · AI 校园助手第二阶段（知识来源、知识切片、向量检索、未回答问题）
-- 执行方式：Supabase Dashboard -> SQL Editor -> New query -> Run
-- 特点：增量迁移，不删除第一阶段已有的 knowledge_documents 数据。
-- 向量模型：text-embedding-v4，固定使用 1024 维。
-- ============================================================================

begin;

create extension if not exists vector with schema extensions;

-- 1. 可采集的学校官方来源。后台管理员维护，爬虫只能处理这里启用的域名。
create table if not exists public.knowledge_sources (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    base_url text not null unique,
    domain text not null,
    source_type text not null default 'official_site'
        check (source_type in ('official_site', 'department_site', 'college_site')),
    default_category text,
    enabled boolean not null default true,
    requires_review boolean not null default true,
    crawl_interval_hours integer not null default 24
        check (crawl_interval_hours between 1 and 720),
    max_pages_per_run integer not null default 40
        check (max_pages_per_run between 1 and 500),
    last_crawled_at timestamptz,
    last_status text not null default 'never'
        check (last_status in ('never', 'ok', 'partial', 'error', 'paused')),
    last_error text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now()),
    check (base_url ~ '^https://'),
    check (domain ~ '^[a-z0-9.-]+$'),
    check (domain = 'sdtbu.edu.cn' or domain like '%.sdtbu.edu.cn')
);

create index if not exists idx_knowledge_sources_enabled
    on public.knowledge_sources (enabled, last_crawled_at);

-- 2. 扩展第一阶段文章表，保留全部旧数据。
alter table public.knowledge_documents
    add column if not exists source_id uuid references public.knowledge_sources(id) on delete set null,
    add column if not exists canonical_url text,
    add column if not exists content_format text not null default 'text'
        check (content_format in ('text', 'html', 'pdf', 'manual')),
    add column if not exists effective_from date,
    add column if not exists effective_until date,
    add column if not exists last_crawled_at timestamptz;

create unique index if not exists idx_knowledge_documents_canonical_url
    on public.knowledge_documents (canonical_url)
    where canonical_url is not null;

create index if not exists idx_knowledge_documents_source_status
    on public.knowledge_documents (source_id, status, updated_at desc);

-- 3. 文章切片与向量。只有服务端和管理员能够读取。
create table if not exists public.knowledge_chunks (
    id uuid primary key default gen_random_uuid(),
    document_id uuid not null references public.knowledge_documents(id) on delete cascade,
    chunk_index integer not null check (chunk_index >= 0),
    title text not null,
    content text not null,
    content_hash text not null,
    embedding extensions.vector(1024),
    embedding_model text not null default 'text-embedding-v4',
    embedding_status text not null default 'queued'
        check (embedding_status in ('queued', 'processing', 'ready', 'failed')),
    last_error text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now()),
    unique (document_id, chunk_index),
    check (char_length(content) between 1 and 6000)
);

create index if not exists idx_knowledge_chunks_document
    on public.knowledge_chunks (document_id, chunk_index);

create index if not exists idx_knowledge_chunks_embedding_status
    on public.knowledge_chunks (embedding_status, updated_at);

create index if not exists idx_knowledge_chunks_embedding_hnsw
    on public.knowledge_chunks
    using hnsw (embedding vector_cosine_ops)
    where embedding is not null;

-- 4. 未回答问题。只保存脱敏后的示例文本和不可逆哈希。
create table if not exists public.unanswered_questions (
    id bigint generated by default as identity primary key,
    question_hash text not null unique,
    sample_question text not null,
    normalized_question text not null,
    topic text not null default '其他',
    ask_count integer not null default 1 check (ask_count > 0),
    status text not null default 'open'
        check (status in ('open', 'reviewing', 'resolved', 'ignored')),
    resolution_document_id uuid references public.knowledge_documents(id) on delete set null,
    metadata jsonb not null default '{}'::jsonb,
    first_asked_at timestamptz not null default timezone('utc'::text, now()),
    last_asked_at timestamptz not null default timezone('utc'::text, now()),
    resolved_at timestamptz,
    updated_at timestamptz not null default timezone('utc'::text, now()),
    check (char_length(question_hash) = 64),
    check (char_length(sample_question) between 1 and 500),
    check (char_length(normalized_question) between 1 and 500)
);

create index if not exists idx_unanswered_questions_priority
    on public.unanswered_questions (status, ask_count desc, last_asked_at desc);

-- 5. 官网采集任务日志。第二阶段下一部分的爬虫会写入这里。
create table if not exists public.crawl_jobs (
    id uuid primary key default gen_random_uuid(),
    source_id uuid references public.knowledge_sources(id) on delete set null,
    status text not null default 'queued'
        check (status in ('queued', 'running', 'succeeded', 'partial', 'failed', 'skipped')),
    pages_scanned integer not null default 0 check (pages_scanned >= 0),
    pages_added integer not null default 0 check (pages_added >= 0),
    pages_updated integer not null default 0 check (pages_updated >= 0),
    pages_failed integer not null default 0 check (pages_failed >= 0),
    error_summary text,
    details jsonb not null default '{}'::jsonb,
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists idx_crawl_jobs_source_created
    on public.crawl_jobs (source_id, created_at desc);

-- 6. 语义检索 RPC。只允许 service_role 调用。
create or replace function public.match_knowledge_chunks(
    p_query_embedding extensions.vector(1024),
    p_match_threshold double precision default 0.55,
    p_match_count integer default 12
)
returns table (
    chunk_id uuid,
    document_id uuid,
    slug text,
    title text,
    category text,
    content text,
    source_url text,
    source_date date,
    verified_at timestamptz,
    semantic_score double precision
)
language sql
stable
security invoker
set search_path = ''
as $$
    select
        c.id,
        d.id,
        d.slug,
        d.title,
        d.category,
        c.content,
        coalesce(d.canonical_url, d.source_url),
        d.source_date,
        d.verified_at,
        1 - (c.embedding OPERATOR(extensions.<=>) p_query_embedding) as semantic_score
    from public.knowledge_chunks c
    join public.knowledge_documents d on d.id = c.document_id
    where d.status = 'published'
      and c.embedding_status = 'ready'
      and c.embedding is not null
      and (d.effective_until is null or d.effective_until >= current_date)
      and 1 - (c.embedding OPERATOR(extensions.<=>) p_query_embedding) >= greatest(0, least(p_match_threshold, 1))
    order by c.embedding OPERATOR(extensions.<=>) p_query_embedding
    limit greatest(1, least(coalesce(p_match_count, 12), 50));
$$;

revoke all on function public.match_knowledge_chunks(
    extensions.vector, double precision, integer
) from public, anon, authenticated;
grant execute on function public.match_knowledge_chunks(
    extensions.vector, double precision, integer
) to service_role;

-- 7. 原子记录未回答问题，避免并发提问导致计数丢失。
create or replace function public.record_unanswered_question(
    p_question_hash text,
    p_sample_question text,
    p_normalized_question text,
    p_topic text,
    p_metadata jsonb default '{}'::jsonb
)
returns table (
    id bigint,
    ask_count integer,
    status text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
    if p_question_hash is null or char_length(p_question_hash) <> 64 then
        raise exception 'invalid question hash';
    end if;

    return query
    insert into public.unanswered_questions as target (
        question_hash,
        sample_question,
        normalized_question,
        topic,
        metadata
    ) values (
        p_question_hash,
        left(p_sample_question, 500),
        left(p_normalized_question, 500),
        left(coalesce(nullif(p_topic, ''), '其他'), 80),
        coalesce(p_metadata, '{}'::jsonb)
    )
    on conflict (question_hash) do update set
        sample_question = excluded.sample_question,
        topic = excluded.topic,
        ask_count = target.ask_count + 1,
        last_asked_at = timezone('utc'::text, now()),
        updated_at = timezone('utc'::text, now()),
        metadata = target.metadata || excluded.metadata
    returning target.id, target.ask_count, target.status;
end;
$$;

revoke all on function public.record_unanswered_question(
    text, text, text, text, jsonb
) from public, anon, authenticated;
grant execute on function public.record_unanswered_question(
    text, text, text, text, jsonb
) to service_role;

-- 8. 所有新表默认私有。管理员只能通过可信 app_metadata.role 访问。
alter table public.knowledge_sources enable row level security;
alter table public.knowledge_chunks enable row level security;
alter table public.unanswered_questions enable row level security;
alter table public.crawl_jobs enable row level security;

revoke all on table public.knowledge_sources from public, anon, authenticated;
revoke all on table public.knowledge_chunks from public, anon, authenticated;
revoke all on table public.unanswered_questions from public, anon, authenticated;
revoke all on table public.crawl_jobs from public, anon, authenticated;

grant select, insert, update, delete on table public.knowledge_sources to authenticated;
grant select on table public.knowledge_chunks to authenticated;
grant select, update on table public.unanswered_questions to authenticated;
grant select on table public.crawl_jobs to authenticated;

grant select, insert, update, delete on table public.knowledge_sources to service_role;
grant select, insert, update, delete on table public.knowledge_chunks to service_role;
grant select, insert, update, delete on table public.unanswered_questions to service_role;
grant select, insert, update, delete on table public.crawl_jobs to service_role;
grant usage, select on sequence public.unanswered_questions_id_seq to service_role;

drop policy if exists knowledge_sources_admin_manage on public.knowledge_sources;
create policy knowledge_sources_admin_manage on public.knowledge_sources
for all to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists knowledge_chunks_admin_read on public.knowledge_chunks;
create policy knowledge_chunks_admin_read on public.knowledge_chunks
for select to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists unanswered_questions_admin_manage on public.unanswered_questions;
create policy unanswered_questions_admin_manage on public.unanswered_questions
for all to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists crawl_jobs_admin_read on public.crawl_jobs;
create policy crawl_jobs_admin_read on public.crawl_jobs
for select to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- 管理员可以维护文章；普通登录用户仍无法读取私有知识库。
grant select, insert, update, delete on table public.knowledge_documents to authenticated;
drop policy if exists knowledge_documents_admin_manage on public.knowledge_documents;
create policy knowledge_documents_admin_manage on public.knowledge_documents
for all to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- 9. 首批官方来源。默认要求人工审核，不会自动进入 AI 正式知识库。
insert into public.knowledge_sources (
    name, base_url, domain, source_type, default_category, requires_review
) values
    ('山东工商学院官网', 'https://www.sdtbu.edu.cn/', 'www.sdtbu.edu.cn', 'official_site', null, true),
    ('党委学生工作部', 'https://xsc.sdtbu.edu.cn/', 'xsc.sdtbu.edu.cn', 'department_site', '校园服务', true),
    ('教务处', 'https://jwc.sdtbu.edu.cn/', 'jwc.sdtbu.edu.cn', 'department_site', '选课教学', true),
    ('信息公开网', 'https://xxgk.sdtbu.edu.cn/', 'xxgk.sdtbu.edu.cn', 'department_site', null, true),
    ('研究生处', 'https://yjs.sdtbu.edu.cn/', 'yjs.sdtbu.edu.cn', 'department_site', '毕业就业', true)
on conflict (base_url) do nothing;

commit;
